version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/p5f6n0i8
      - REPOSITORY_URI=public.ecr.aws/p5f6n0i8/lesson14-df
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t lesson14-df files/df
      - docker tag lesson14-df:latest public.ecr.aws/p5f6n0i8/lesson14-df:latest
  post_build:
    commands:
      - echo Build completed
      - echo Pushing the Docker images...
      - docker push public.ecr.aws/p5f6n0i8/lesson14-df:latest
      - echo Writing definitions file...
      - printf '[{"name":"project-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > taskdefinition.json
artifacts:
    files: taskdefinition.json