version: 0.2
phases:
  build:
    commands:
      - echo Build started
      - echo Building the Docker image...          
  post_build:
    commands:
      - echo Build completed
      - echo Pushing the Docker images...
